/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EstimateInboundMessageFeeRequestMessage {
    #[serde(rename = "version")]
    pub version: f32,
    #[serde(rename = "nonce")]
    pub nonce: f32,
    #[serde(rename = "originDomain")]
    pub origin_domain: f32,
    #[serde(rename = "sender")]
    pub sender: String,
    #[serde(rename = "destinationDomain")]
    pub destination_domain: f32,
    #[serde(rename = "recipient")]
    pub recipient: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl EstimateInboundMessageFeeRequestMessage {
    pub fn new(version: f32, nonce: f32, origin_domain: f32, sender: String, destination_domain: f32, recipient: String, message: String) -> EstimateInboundMessageFeeRequestMessage {
        EstimateInboundMessageFeeRequestMessage {
            version,
            nonce,
            origin_domain,
            sender,
            destination_domain,
            recipient,
            message,
        }
    }
}


