/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EstimateInboundMessageFeeRequest {
    #[serde(rename = "origin")]
    pub origin: u32,
    #[serde(rename = "originMailbox")]
    pub origin_mailbox: String,
    #[serde(rename = "checkpointRoot")]
    pub checkpoint_root: String,
    #[serde(rename = "checkpointIndex")]
    pub checkpoint_index: u32,
    #[serde(rename = "message")]
    pub message: Box<crate::models::EstimateInboundMessageFeeRequestMessage>,
    #[serde(rename = "signatures")]
    pub signatures: Vec<String>,
}

impl EstimateInboundMessageFeeRequest {
    pub fn new(origin: u32, origin_mailbox: String, checkpoint_root: String, checkpoint_index: u32, message: crate::models::EstimateInboundMessageFeeRequestMessage, signatures: Vec<String>) -> EstimateInboundMessageFeeRequest {
        EstimateInboundMessageFeeRequest {
            origin,
            origin_mailbox,
            checkpoint_root,
            checkpoint_index,
            message: Box::new(message),
            signatures,
        }
    }
}


