/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EstimateInboundMessageFee200Response {
    #[serde(rename = "feeLovelace")]
    pub fee_lovelace: f32,
}

impl EstimateInboundMessageFee200Response {
    pub fn new(fee_lovelace: f32) -> EstimateInboundMessageFee200Response {
        EstimateInboundMessageFee200Response {
            fee_lovelace,
        }
    }
}


