/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetValidatorStorageLocations200ResponseValidatorStorageLocationsInner {
    #[serde(rename = "validatorAddress")]
    pub validator_address: String,
    #[serde(rename = "storageLocation")]
    pub storage_location: String,
}

impl GetValidatorStorageLocations200ResponseValidatorStorageLocationsInner {
    pub fn new(validator_address: String, storage_location: String) -> GetValidatorStorageLocations200ResponseValidatorStorageLocationsInner {
        GetValidatorStorageLocations200ResponseValidatorStorageLocationsInner {
            validator_address,
            storage_location,
        }
    }
}


