/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOutboundGasPayment200Response {
    #[serde(rename = "totalGasADA")]
    pub total_gas_ada: f32,
}

impl GetOutboundGasPayment200Response {
    pub fn new(total_gas_ada: f32) -> GetOutboundGasPayment200Response {
        GetOutboundGasPayment200Response {
            total_gas_ada,
        }
    }
}


