/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOutboundGasPaymentRequest {
    #[serde(rename = "relayerAddress")]
    pub relayer_address: String,
    #[serde(rename = "messageId")]
    pub message_id: String,
}

impl GetOutboundGasPaymentRequest {
    pub fn new(relayer_address: String, message_id: String) -> GetOutboundGasPaymentRequest {
        GetOutboundGasPaymentRequest {
            relayer_address,
            message_id,
        }
    }
}


