/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InboxIsmParameters200Response {
    #[serde(rename = "validators")]
    pub validators: Vec<String>,
    #[serde(rename = "threshold")]
    pub threshold: u32,
}

impl InboxIsmParameters200Response {
    pub fn new(validators: Vec<String>, threshold: u32) -> InboxIsmParameters200Response {
        InboxIsmParameters200Response {
            validators,
            threshold,
        }
    }
}


