/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MerkleTree200ResponseMerkleTree {
    #[serde(rename = "count")]
    pub count: u32,
    #[serde(rename = "branches")]
    pub branches: Vec<String>,
}

impl MerkleTree200ResponseMerkleTree {
    pub fn new(count: u32, branches: Vec<String>) -> MerkleTree200ResponseMerkleTree {
        MerkleTree200ResponseMerkleTree {
            count,
            branches,
        }
    }
}


