/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MessagesByBlockRange200ResponseMessagesInner {
    #[serde(rename = "block")]
    pub block: u32,
    #[serde(rename = "message")]
    pub message: Box<crate::models::MessagesByBlockRange200ResponseMessagesInnerMessage>,
}

impl MessagesByBlockRange200ResponseMessagesInner {
    pub fn new(block: u32, message: crate::models::MessagesByBlockRange200ResponseMessagesInnerMessage) -> MessagesByBlockRange200ResponseMessagesInner {
        MessagesByBlockRange200ResponseMessagesInner {
            block,
            message: Box::new(message),
        }
    }
}


