/*
 * Hyperlane <> Cardano RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitInboundMessage200Response {
    #[serde(rename = "txId")]
    pub tx_id: String,
}

impl SubmitInboundMessage200Response {
    pub fn new(tx_id: String) -> SubmitInboundMessage200Response {
        SubmitInboundMessage200Response {
            tx_id,
        }
    }
}


