/*
 * Outbox RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MerkleTreeByBlockNumber200ResponseMerkleTree {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "branches")]
    pub branches: Vec<String>,
}

impl MerkleTreeByBlockNumber200ResponseMerkleTree {
    pub fn new(count: i32, branches: Vec<String>) -> MerkleTreeByBlockNumber200ResponseMerkleTree {
        MerkleTreeByBlockNumber200ResponseMerkleTree {
            count,
            branches,
        }
    }
}


