/*
 * Outbox RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MerkleTreesByBlockNumber200Response {
    #[serde(rename = "blockNumber")]
    pub block_number: i32,
    #[serde(rename = "merkleTrees")]
    pub merkle_trees: Vec<crate::models::MerkleTreesByBlockNumber200ResponseMerkleTreesInner>,
}

impl MerkleTreesByBlockNumber200Response {
    pub fn new(block_number: i32, merkle_trees: Vec<crate::models::MerkleTreesByBlockNumber200ResponseMerkleTreesInner>) -> MerkleTreesByBlockNumber200Response {
        MerkleTreesByBlockNumber200Response {
            block_number,
            merkle_trees,
        }
    }
}


