/*
 * Outbox RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MerkleTreeByBlockNumber200ResponseMerkleTree {
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "branches", skip_serializing_if = "Option::is_none")]
    pub branches: Option<Vec<String>>,
}

impl MerkleTreeByBlockNumber200ResponseMerkleTree {
    pub fn new() -> MerkleTreeByBlockNumber200ResponseMerkleTree {
        MerkleTreeByBlockNumber200ResponseMerkleTree {
            count: None,
            branches: None,
        }
    }
}


