/*
 * Outbox RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MerkleTreeByBlockNumber200Response {
    #[serde(rename = "blockNumber", skip_serializing_if = "Option::is_none")]
    pub block_number: Option<i32>,
    #[serde(rename = "merkleTree", skip_serializing_if = "Option::is_none")]
    pub merkle_tree: Option<Box<crate::models::MerkleTreeByBlockNumber200ResponseMerkleTree>>,
}

impl MerkleTreeByBlockNumber200Response {
    pub fn new() -> MerkleTreeByBlockNumber200Response {
        MerkleTreeByBlockNumber200Response {
            block_number: None,
            merkle_tree: None,
        }
    }
}


