/*
 * Outbox RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MessagesByBlockRange200ResponseMessagesInner {
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<i32>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<Box<crate::models::MessagesByBlockRange200ResponseMessagesInnerMessage>>,
}

impl MessagesByBlockRange200ResponseMessagesInner {
    pub fn new() -> MessagesByBlockRange200ResponseMessagesInner {
        MessagesByBlockRange200ResponseMessagesInner {
            block: None,
            message: None,
        }
    }
}


