/*
 * Outbox RPC API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MessagesByBlockRange200ResponseMessagesInnerMessage {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "nonce")]
    pub nonce: i32,
    #[serde(rename = "originDomain")]
    pub origin_domain: String,
    #[serde(rename = "sender")]
    pub sender: String,
    #[serde(rename = "destinationDomain")]
    pub destination_domain: String,
    #[serde(rename = "recipient")]
    pub recipient: String,
    #[serde(rename = "body")]
    pub body: String,
}

impl MessagesByBlockRange200ResponseMessagesInnerMessage {
    pub fn new(version: i32, nonce: i32, origin_domain: String, sender: String, destination_domain: String, recipient: String, body: String) -> MessagesByBlockRange200ResponseMessagesInnerMessage {
        MessagesByBlockRange200ResponseMessagesInnerMessage {
            version,
            nonce,
            origin_domain,
            sender,
            destination_domain,
            recipient,
            body,
        }
    }
}


