openapi: 3.0.0
info:
  title: Outbox RPC API
  version: 1.0.0
paths:
  /api/outbox/messages:
    get:
      summary: Get all messages from the outbox
      responses:
        200:
          description: An array of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
              examples:
                empty:
                  value: []
                oneMessage:
                  value:
                    - id: 1
                      content: "First message"
                multipleMessages:
                  value:
                    - id: 1
                      content: "First custom message"
                    - id: 2
                      content: "Second custom message"
                    - id: 3
                      content: "Third custom message"
                    - id: 4
                      content: "Fourth custom message"
                    - id: 5
                      content: "Fifth custom message"
components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
