### Last finalized block
GET http://127.0.0.1:3000/api/indexer/lastFinalizedBlock

### MerkleTree
GET http://127.0.0.1:3000/api/indexer/merkleTree

### Messages
GET http://127.0.0.1:3000/api/indexer/messages/9/10