apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-checkpoints-volume
  labels:
    volume: local-checkpoints-volume
spec:
  storageClassName: local-checkpoints
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: HOME_PLACEHOLDER/.local-hyperlane-checkpoints
    type: DirectoryOrCreate