# Default values for hyperlane-validator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: Always

#  repository: ghcr.io/tvl-labs/hyperlane-monorepo
#  tag: "2a85153a17c846d292dd13ecc58059552144d7f1"

# Use the locally built image.
  repository: host.docker.internal:5000/hyperlane-cardano-local
  tag: "20230808102044"

validator:
  originChain: ""
  originChainRpc: ""
  originChainEnvName: ""
  privateKey: ""
  localCheckpointsSubPath: ""
  reorgPeriod: 0
  interval: 1
  useBlake2MerkleTree: false

imagePullSecrets:
  - name: ghcr-login-secret

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: true

service:
  type: ClusterIP
  metrics:
    port: 9090

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
