# Default values for hyperlane-relayer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: Always

#  repository: ghcr.io/tvl-labs/hyperlane-monorepo
#  tag: "2a85153a17c846d292dd13ecc58059552144d7f1"

# Use the locally built image.
  repository: host.docker.internal:5000/hyperlane-cardano-local
  tag: "20230903142837"

imagePullSecrets:
  - name: ghcr-login-secret
nameOverride: ""
fullnameOverride: ""

relayer:
  originChain: ""
  originChainRpc: ""
  destinationChain: ""
  destinationChainEnv: ""
  destinationChainRpc: ""
  privateKey: ""
  useBlake2MerkleTree: false
  extraGas: "50000" # Default value of the Hyperlane https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/c7ad0f4433f6661bf930fe6d6581c1187da84692/rust/chains/hyperlane-ethereum/src/tx.rs#L16

serviceAccount:
  create: true

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  metrics:
    port: 9090

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
