{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperlane-relayer.serviceAccountName" . }}
  labels:
    {{- include "hyperlane-relayer.labels" . | nindent 4 }}
{{- end }}
