apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperlane-relayer.fullname" . }}
  labels:
    {{- include "hyperlane-relayer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      name: metrics
  selector:
    {{- include "hyperlane-relayer.selectorLabels" . | nindent 4 }}
