### Last finalized block
GET http://127.0.0.1:3001/api/indexer/lastFinalizedBlock

### MerkleTree
GET http://127.0.0.1:3001/api/indexer/merkleTree

### Messages
GET http://127.0.0.1:3001/api/indexer/messages/9/10

### Validator storage locations
POST http://127.0.0.1:3001/api/validator-announcement/get-storage-locations/
Content-Type: application/json

{
  "validatorAddresses": [
    "0x00000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8"
  ]
}