validator:
  originChain: "fuji"
  originChainRpc: "https://rpc.ankr.com/avalanche_fuji"
  originChainEnvName: "FUJI"
  # Private key of validator 0x268A18f088F32567Ae70e7dd74dc658AC98F322F
  privateKey: "0x1f0a8216679a21914782570ce9ea5453d0ffa8262c47f01bd36611c7225fc0b8"
  localCheckpointsSubPath: "0x268A18f088F32567Ae70e7dd74dc658AC98F322F"
  useBlake2MerkleTree: false
  # TODO: check these values.
  reorgPeriod: 1
  interval: 1