apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hyperlane-validator.localCheckpointsPersistentVolumeClaimName" . }}
spec:
  storageClassName: local-checkpoints
  selector:
    matchLabels:
      volume: local-checkpoints-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
