apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cardano.rpc.fullname" . }}
  labels:
    {{- include "cardano.rpc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cardano.rpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cardano.rpc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cardano.rpc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MOCK_ENV
              value: "true"
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: BLOCKFROST_PREFIX
              value: "https://cardano-preprod.blockfrost.io/api/v0"
            - name: BLOCKFROST_PROJECT_ID
              value: "preprodbsnaSdm0tOwT9Ifr1ynCXnMpz9MBZhRm"
            - name: OUTBOX_AUTH_TOKEN
              value: "59c5610462c406da578e1db73f1d2d8d0e8378add7351d80da9bc41f61757468"
            - name: ISM_VALIDATOR_PUB_KEY_1
              value: "035f49177825e10b520389c552cb22e114c6b4508a5387ff327b2e7fdd90d12410"
            - name: ISM_VALIDATOR_PUB_KEY_2
              value: "028977e37b8af0384e1ea01a748bf7ef2b4a73c17c634910eb03c4ce0a38efa16d"
            - name: ISM_VALIDATOR_PUB_KEY_3
              value: "03501e4f7eab5fad2409b66588be82e244073c9ca085c69e2ab69eb470346fbaeb"
            - name: ISM_THRESHOLD
              value: "2"
            - name: WALLET_ADDRESS
              value: "addr_test1vqvjvk3qezccu5a3gce65mqvg4tpfy47plv68wmh68paswqv3jaqe"
            - name: WALLET_PRIVATE_KEY
              value: "e8e34f6c74e22577d609803dfe9c8773f10e478e7dadf6d065a78ae42a21f912"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /config/config.json
              name: cardano-rpc-config
              readOnly: true
              subPath: config.json
{{/*  TODO: implement /api/health   livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /api/health*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /api/health*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cardano-rpc-config
          configMap:
            name: {{ include "cardano.rpc.configMapName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
