apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cardano.rpc.fullname" . }}
  namespace: monitoring
  labels:
    metrics: "true"
spec:
  selector:
    matchLabels:
      {{- include "cardano.rpc.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - applications
  endpoints:
    - port: http
      path: /metrics
      honorLabels: true